# Generated by Django 5.0.7 on 2024-07-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("about", models.TextField()),
                ("logo", models.ImageField(upload_to="clubs_logos/")),
                ("color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("password", models.CharField(max_length=255)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        default="path_to_default_image", upload_to="event_covers/"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("summary", models.CharField(max_length=150)),
                ("members_only", models.BooleanField(default=False)),
                ("highlight", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_events",
                        to="mainapp.club",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="events",
            field=models.ManyToManyField(related_name="clubs", to="mainapp.event"),
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mainapp.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("mainapp.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mainapp.user",
                    ),
                ),
                (
                    "class_level",
                    models.CharField(
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "clubs",
                    models.ManyToManyField(related_name="students", to="mainapp.club"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("mainapp.user",),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(upload_to="news_covers/")),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("summary", models.CharField(max_length=150)),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SR", "Senior"),
                            ("JR", "Junior"),
                            ("SO", "Sophomore"),
                            ("FR", "Freshman"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("highlight", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Varsity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("about", models.TextField()),
                ("logo", models.ImageField(upload_to="varsities_logos/")),
                ("color", models.CharField(max_length=7)),
                (
                    "events",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.event"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="varsity_memberships", to="mainapp.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="varsities",
            field=models.ManyToManyField(related_name="students", to="mainapp.varsity"),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_highlight_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_event_highlight_1",
                        to="mainapp.event",
                    ),
                ),
                (
                    "event_highlight_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_event_highlight_2",
                        to="mainapp.event",
                    ),
                ),
                (
                    "event_highlight_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_event_highlight_3",
                        to="mainapp.event",
                    ),
                ),
                (
                    "news_highlight_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_news_highlight_1",
                        to="mainapp.news",
                    ),
                ),
                (
                    "news_highlight_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_news_highlight_2",
                        to="mainapp.news",
                    ),
                ),
                (
                    "news_highlight_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_news_highlight_3",
                        to="mainapp.news",
                    ),
                ),
                (
                    "officer_highlight_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_officer_highlight_1",
                        to="mainapp.student",
                    ),
                ),
                (
                    "officer_highlight_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_officer_highlight_2",
                        to="mainapp.student",
                    ),
                ),
                (
                    "officer_highlight_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_officer_highlight_3",
                        to="mainapp.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="heads",
            field=models.ManyToManyField(
                related_name="head_clubs", to="mainapp.student"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="leadership",
            field=models.ManyToManyField(
                related_name="leadership_roles", to="mainapp.student"
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                related_name="membership_clubs", to="mainapp.student"
            ),
        ),
    ]
