# Generated by Django 5.2.5 on 2025-08-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bylaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_db_id', models.CharField(help_text='Faculty ID', max_length=20, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, default='default-pfp.png', null=True, upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('answer', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('student', 'Student FAQ'), ('clubhead', 'Club Heads FAQ'), ('faculty', 'Faulty FAQ'), ('ssofficer', 'SS Officer FAQ'), ('releasenotes', 'Release Notes')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_db_id', models.CharField(help_text='Student ID', max_length=20, primary_key=True, serialize=False)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1)),
                ('profile_picture', models.ImageField(blank=True, default='default-pfp.png', null=True, upload_to='profiles/')),
                ('about', models.TextField(blank=True, null=True)),
                ('year_level_title', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('male', 'Boys Only'), ('female', 'Girls Only'), ('mixed', 'Mixed Club')], default='mixed', max_length=6)),
                ('about', models.TextField()),
                ('logo', models.ImageField(upload_to='clubs_logos/')),
                ('color', models.CharField(max_length=7)),
                ('advisors', models.ManyToManyField(blank=True, related_name='advisor_clubs', to=settings.AUTH_USER_MODEL)),
                ('bylaws', models.ManyToManyField(blank=True, related_name='club_bylaws', to='mainapp.bylaw')),
                ('heads', models.ManyToManyField(blank=True, related_name='head_clubs', to=settings.AUTH_USER_MODEL)),
                ('leadership', models.ManyToManyField(blank=True, related_name='leadership_roles', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='membership_clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddByLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=10000)),
                ('expiry', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_addbylink_hash', to='mainapp.club')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='associated_clubs',
            field=models.ManyToManyField(blank=True, related_name='associated_clubs', to='mainapp.club'),
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainapp.club',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('summary', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('group', models.CharField(choices=[('ngr', 'All Year Levels'), ('12', 'Senior'), ('11', 'Junior'), ('10', 'Sophomore'), ('9', 'Freshman')], default='ngr', max_length=3)),
                ('grade', models.CharField(choices=[('nosec', 'All Sections'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], default='nosec', max_length=5)),
                ('attendance_locked', models.BooleanField(default=False)),
                ('members_only', models.BooleanField(default=False)),
                ('highlight', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('hos_approved', models.BooleanField(default=False)),
                ('significant_event', models.BooleanField(default=False)),
                ('attending_Students', models.ManyToManyField(blank=True, related_name='attending_students', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_events', to='mainapp.club')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_color', to='mainapp.club')),
                ('confirmed_Students', models.ManyToManyField(blank=True, related_name='confirm_students', to=settings.AUTH_USER_MODEL)),
                ('links', models.ManyToManyField(blank=True, related_name='events_links', to='mainapp.links')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='mainapp.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='associated_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty'),
        ),
        migrations.AddField(
            model_name='club',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='club_links', to='mainapp.links'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='news_covers/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(max_length=150)),
                ('group', models.CharField(choices=[('ngr', 'All Year Levels'), ('12', 'Senior'), ('11', 'Junior'), ('10', 'Sophomore'), ('9', 'Freshman')], default='ngr', max_length=3)),
                ('grade', models.CharField(choices=[('nosec', 'All Sections'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], default='nosec', max_length=5)),
                ('highlight', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('awaiting_approval', models.BooleanField(default=True)),
                ('draft', models.BooleanField(default=False)),
                ('denied_reason', models.CharField(blank=True, max_length=150, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('links', models.ManyToManyField(blank=True, related_name='news_links', to='mainapp.links')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_scroll_duration', models.IntegerField(default=2000, help_text='Time Before Carousel Autoscrolls (ms)')),
                ('event_highlight_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_event_highlight_1', to='mainapp.event')),
                ('event_highlight_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_event_highlight_2', to='mainapp.event')),
                ('event_highlight_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_event_highlight_3', to='mainapp.event')),
                ('officer_highlight_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_1', to=settings.AUTH_USER_MODEL)),
                ('officer_highlight_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_2', to=settings.AUTH_USER_MODEL)),
                ('officer_highlight_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_3', to=settings.AUTH_USER_MODEL)),
                ('officer_highlight_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_4', to=settings.AUTH_USER_MODEL)),
                ('news_highlight_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_news_highlight_1', to='mainapp.news')),
                ('news_highlight_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_news_highlight_2', to='mainapp.news')),
                ('news_highlight_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_news_highlight_3', to='mainapp.news')),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('attended_Students', models.ManyToManyField(blank=True, related_name='plc_attended_students', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc_facilitator', to=settings.AUTH_USER_MODEL)),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc_recorder', to=settings.AUTH_USER_MODEL)),
                ('timekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc_timekeeper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('draft', models.BooleanField(default=False)),
                ('hos_approved', models.BooleanField(default=False)),
                ('attending_Members', models.ManyToManyField(blank=True, related_name='meeting_attending_members', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_meetings', to='mainapp.club')),
                ('links', models.ManyToManyField(blank=True, related_name='emeeting_links', to='mainapp.links')),
                ('plc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc', to='mainapp.plc')),
            ],
        ),
        migrations.CreateModel(
            name='PLCAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_action_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plc',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='plc_actions', to='mainapp.plcaction'),
        ),
        migrations.CreateModel(
            name='PLCTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_topic_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plc',
            name='focus_topics',
            field=models.ManyToManyField(blank=True, related_name='plc_topics', to='mainapp.plctopic'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('type', models.CharField(choices=[('link', 'Website Link'), ('file', 'Uploaded File')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.links')),
            ],
        ),
        migrations.AddField(
            model_name='bylaw',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='bylaw_resources', to='mainapp.resource'),
        ),
        migrations.AddField(
            model_name='user',
            name='associated_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student'),
        ),
        migrations.CreateModel(
            name='Varsity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('logo', models.ImageField(upload_to='varsities_logos/')),
                ('color', models.CharField(max_length=7)),
                ('captains', models.ManyToManyField(blank=True, related_name='varsity_captains', to=settings.AUTH_USER_MODEL)),
                ('coaches', models.ManyToManyField(blank=True, related_name='varsity_coaches', to=settings.AUTH_USER_MODEL)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.event')),
                ('links', models.ManyToManyField(blank=True, related_name='varsity_links', to='mainapp.links')),
                ('members', models.ManyToManyField(blank=True, related_name='varsity_players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='associated_varsities',
            field=models.ManyToManyField(blank=True, related_name='associated_varsity', to='mainapp.varsity'),
        ),
    ]
