# Generated by Django 5.0.7 on 2024-07-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="clubs", to="mainapp.event"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="heads",
            field=models.ManyToManyField(
                blank=True, related_name="head_clubs", to="mainapp.student"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="leadership",
            field=models.ManyToManyField(
                blank=True, related_name="leadership_roles", to="mainapp.student"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="membership_clubs", to="mainapp.student"
            ),
        ),
        migrations.AlterField(
            model_name="varsity",
            name="events",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.event",
            ),
        ),
        migrations.AlterField(
            model_name="varsity",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="varsity_memberships", to="mainapp.student"
            ),
        ),
    ]
