# Generated by Django 5.0.7 on 2024-07-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_club_events_alter_club_heads_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="event_covers/"),
        ),
    ]
