# Generated by Django 5.0.7 on 2024-07-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_event_date_news_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateField(),
        ),
    ]
