# Generated by Django 5.0.7 on 2024-07-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_alter_event_date_alter_news_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
