# Generated by Django 5.0.7 on 2024-07-15 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0006_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_color",
                to="mainapp.club",
            ),
        ),
    ]
