# Generated by Django 5.0.7 on 2024-07-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_event_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="grade",
            new_name="section",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="class_level",
            new_name="year_level",
        ),
        migrations.AlterField(
            model_name="student",
            name="clubs",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="mainapp.club"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="varsities",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="mainapp.varsity"
            ),
        ),
    ]
