# Generated by Django 5.0.7 on 2024-07-15 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0008_rename_grade_student_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
