# Generated by Django 5.0.7 on 2024-07-15 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0009_alter_news_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="varsity",
            name="events",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.event",
            ),
        ),
    ]
