# Generated by Django 5.0 on 2024-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0011_alter_faculty_options_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="department",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="clubs",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="mainapp.club"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default-pfp.png/", null=True, upload_to="profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                    ("H", "H"),
                    ("I", "I"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="varsities",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="mainapp.varsity"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_level",
            field=models.CharField(
                choices=[
                    ("FR", "Freshman"),
                    ("SO", "Sophomore"),
                    ("JR", "Junior"),
                    ("SR", "Senior"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=60, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
