# Generated by Django 5.0 on 2024-07-16 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mainapp",
            "0013_club_content_type_club_object_id_event_content_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socials",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="club",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="club",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="event",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="news",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="news",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="varsity",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="varsity",
            name="object_id",
        ),
        migrations.DeleteModel(
            name="Links",
        ),
        migrations.DeleteModel(
            name="Socials",
        ),
    ]
