# Generated by Django 5.0 on 2024-07-17 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mainapp",
            "0014_remove_socials_content_type_remove_club_content_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="officer_highlight_4",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_officer_highlight_4",
                to="mainapp.student",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="officer_highlight_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_officer_highlight_1",
                to="mainapp.student",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="officer_highlight_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_officer_highlight_2",
                to="mainapp.student",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="officer_highlight_3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_officer_highlight_3",
                to="mainapp.student",
            ),
        ),
    ]
