# Generated by Django 5.0 on 2024-07-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0015_homepage_officer_highlight_4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="associated_club",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.club",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="associated_faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.faculty",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="associated_student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.student",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="associated_varsity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.varsity",
            ),
        ),
    ]
