# Generated by Django 5.0.6 on 2024-07-29 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='student',
            name='student_db_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
