# Generated by Django 5.0.6 on 2024-07-29 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_student_user_ptr_student_student_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_db_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
