# Generated by Django 5.0.6 on 2024-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_faculty_user_ptr_faculty_faculty_db_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_db_id',
            field=models.CharField(help_text='Student ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
