# Generated by Django 5.0 on 2024-07-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0022_remove_faculty_user_ptr_alter_student_student_db_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
