# Generated by Django 5.0.6 on 2024-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_news_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendingStudents',
            field=models.ManyToManyField(blank=True, related_name='attending_students', to='mainapp.student'),
        ),
    ]
