# Generated by Django 5.0.6 on 2024-08-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_event_attendingstudents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendingStudents',
            new_name='attending_Students',
        ),
    ]
