# Generated by Django 5.0.6 on 2024-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_rename_attendingstudents_event_attending_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_db_id',
            field=models.CharField(help_text='Faculty ID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
