# Generated by Django 5.0.6 on 2024-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_faculty_faculty_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-pfp.png/', null=True, upload_to='profiles/'),
        ),
    ]
