# Generated by Django 5.0.6 on 2024-08-30 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_faculty_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='head_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='leadership',
            field=models.ManyToManyField(blank=True, related_name='leadership_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='membership_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
