# Generated by Django 5.0.6 on 2024-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_club_heads_alter_club_leadership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
