# Generated by Django 5.0.6 on 2024-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_student_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_level_title',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
