# Generated by Django 5.0.6 on 2024-09-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_student_year_level_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='social_links',
            field=models.ManyToManyField(blank=True, related_name='club_social_links', to='mainapp.links'),
        ),
    ]
