# Generated by Django 5.0.6 on 2024-09-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_links_club_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='events_links', to='mainapp.links'),
        ),
        migrations.AddField(
            model_name='news',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='news_links', to='mainapp.links'),
        ),
        migrations.AddField(
            model_name='varsity',
            name='social_links',
            field=models.ManyToManyField(blank=True, related_name='varsity_social_links', to='mainapp.links'),
        ),
    ]
