# Generated by Django 5.0.6 on 2024-09-01 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_event_links_news_links_varsity_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='varsity',
            name='members',
        ),
        migrations.RemoveField(
            model_name='varsity',
            name='social_links',
        ),
        migrations.AddField(
            model_name='club',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='club_links', to='mainapp.links'),
        ),
        migrations.AddField(
            model_name='varsity',
            name='captains',
            field=models.ManyToManyField(blank=True, related_name='varsity_captains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='varsity',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='varsity_links', to='mainapp.links'),
        ),
        migrations.AddField(
            model_name='varsity',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='varsity_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
