# Generated by Django 5.0.6 on 2024-09-01 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_remove_club_social_links_remove_varsity_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varsity',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='varsity_coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
