# Generated by Django 5.0.6 on 2024-09-01 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_varsity_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='advisor_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
