# Generated by Django 5.0.6 on 2024-09-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_club_advisors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='id',
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False),
        ),
    ]
