# Generated by Django 5.0.6 on 2024-09-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_remove_links_id_alter_links_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
