# Generated by Django 5.0.6 on 2024-09-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_alter_event_attending_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='significant_event',
            field=models.BooleanField(default=False),
        ),
    ]
