# Generated by Django 5.0.6 on 2024-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_event_significant_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
