# Generated by Django 5.0.6 on 2024-09-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_links_id_alter_links_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varsity',
            old_name='players',
            new_name='members',
        ),
    ]
