# Generated by Django 5.0.6 on 2024-09-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_alter_news_grade_alter_news_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='group',
            field=models.CharField(choices=[('ngr', 'All Year Levels'), ('SR', 'Senior'), ('JR', 'Junior'), ('SO', 'Sophomore'), ('FR', 'Freshman')], default='ngr', max_length=3),
        ),
    ]
