# Generated by Django 5.0.6 on 2024-09-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_event_grade_event_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='email',
        ),
        migrations.RemoveField(
            model_name='club',
            name='password',
        ),
    ]
