# Generated by Django 5.0.6 on 2024-09-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_remove_club_email_remove_club_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-pfp.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-pfp.png', null=True, upload_to='profiles/'),
        ),
    ]
