# Generated by Django 5.0.6 on 2024-09-11 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_alter_faculty_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='officer_highlight_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='officer_highlight_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='officer_highlight_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='officer_highlight_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_officer_highlight_4', to=settings.AUTH_USER_MODEL),
        ),
    ]
