# Generated by Django 5.0.6 on 2024-09-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_alter_homepage_officer_highlight_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='associated_club',
        ),
        migrations.AddField(
            model_name='user',
            name='associated_club',
            field=models.ManyToManyField(blank=True, related_name='associated_clubs', to='mainapp.club'),
        ),
    ]
