# Generated by Django 5.0.6 on 2024-09-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_remove_user_associated_club_user_associated_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='associated_club',
            new_name='associated_clubs',
        ),
    ]
