# Generated by Django 5.0.6 on 2024-09-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_rename_associated_club_user_associated_clubs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='associated_varsity',
            new_name='associated_varsities',
        ),
        migrations.AlterField(
            model_name='user',
            name='associated_clubs',
            field=models.ManyToManyField(blank=True, related_name='associated_clubss', to='mainapp.club'),
        ),
    ]
