# Generated by Django 5.0.6 on 2024-09-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_rename_associated_varsity_user_associated_varsities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='associated_clubs',
            field=models.ManyToManyField(blank=True, related_name='associated_clubs', to='mainapp.club'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='associated_varsities',
        ),
        migrations.AddField(
            model_name='user',
            name='associated_varsities',
            field=models.ManyToManyField(blank=True, related_name='associated_varsity', to='mainapp.varsity'),
        ),
    ]
