# Generated by Django 5.0.6 on 2024-09-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_alter_user_associated_clubs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varsity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='varsity',
            name='password',
        ),
    ]
