# Generated by Django 5.0.6 on 2024-09-13 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_remove_varsity_email_remove_varsity_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='mainapp.event'),
        ),
        migrations.CreateModel(
            name='Scouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('logo', models.ImageField(upload_to='clubs_logos/')),
                ('color', models.CharField(max_length=7)),
                ('events', models.ManyToManyField(blank=True, related_name='scout_events', to='mainapp.event')),
                ('members', models.ManyToManyField(blank=True, related_name='scout_members', to=settings.AUTH_USER_MODEL)),
                ('scout_leaders', models.ManyToManyField(blank=True, related_name='scout_leaders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
