# Generated by Django 5.0.6 on 2024-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_alter_club_events_scouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associated_scouts',
            field=models.ManyToManyField(blank=True, related_name='associated_scouts', to='mainapp.scouts'),
        ),
    ]
