# Generated by Django 5.0.6 on 2024-09-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_alter_homepage_event_highlight_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel_scroll_duration',
            field=models.IntegerField(default=2000, help_text='Time Before Carousel Autoscrolls (ms)'),
        ),
    ]
