# Generated by Django 5.0.6 on 2024-10-09 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0062_student_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed_Students',
            field=models.ManyToManyField(blank=True, related_name='confirm_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
