# Generated by Django 5.0.6 on 2024-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0064_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
