# Generated by Django 5.0.6 on 2024-10-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0067_remove_meeting_heads_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='cover',
        ),
    ]
