# Generated by Django 5.0.6 on 2024-10-22 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0068_remove_meeting_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='group',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='summary',
        ),
        migrations.AddField(
            model_name='meeting',
            name='attending_Faculty',
            field=models.ManyToManyField(blank=True, related_name='meeting_attending_faculty', to=settings.AUTH_USER_MODEL),
        ),
    ]
