# Generated by Django 5.0.6 on 2024-10-22 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0069_remove_meeting_grade_remove_meeting_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attending_Faculty',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='attending_Students',
        ),
        migrations.AddField(
            model_name='meeting',
            name='attending_Members',
            field=models.ManyToManyField(blank=True, related_name='meeting_attending_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
