# Generated by Django 5.0.6 on 2024-10-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0071_club_type_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='type',
            field=models.CharField(choices=[('male', 'Boys Only'), ('female', 'Girls Only'), ('mixed', 'Mixed Club')], default='mixed', max_length=6),
        ),
    ]
