# Generated by Django 5.0.6 on 2024-10-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0072_alter_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
