# Generated by Django 5.0.6 on 2024-11-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0075_bylaw_text_alter_bylaw_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
