# Generated by Django 5.0.6 on 2024-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0076_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='bylaws',
            field=models.ManyToManyField(blank=True, related_name='club_bylaws', to='mainapp.bylaw'),
        ),
    ]
