# Generated by Django 5.0.6 on 2024-11-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0078_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_locked',
            field=models.BooleanField(default=False),
        ),
    ]
