# Generated by Django 5.0.6 on 2024-11-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0079_event_attendance_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('answer', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('student', 'Student FAQ'), ('clubhead', 'Club Heads FAQ'), ('faculty', 'Faulty FAQ'), ('ssofficer', 'SS Officer FAQ')], max_length=10)),
            ],
        ),
    ]
