# Generated by Django 5.0.6 on 2024-11-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0080_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddByLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=10000)),
                ('expiry', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_addbylink_hash', to='mainapp.club')),
            ],
        ),
    ]
