# Generated by Django 5.0.6 on 2024-11-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0081_addbylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='type',
            field=models.CharField(choices=[('student', 'Student FAQ'), ('clubhead', 'Club Heads FAQ'), ('faculty', 'Faulty FAQ'), ('ssofficer', 'SS Officer FAQ'), ('releasenotes', 'Release Notes')], max_length=50),
        ),
        migrations.CreateModel(
            name='PLCAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_action_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PLCTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_topic_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('expiry', models.DateTimeField()),
                ('attending_Students', models.ManyToManyField(blank=True, related_name='plc_attending_students', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_plc_club', to='mainapp.club')),
                ('confirmed_Students', models.ManyToManyField(blank=True, related_name='plc_confirmed_students', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_plc_facilitator', to=settings.AUTH_USER_MODEL)),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_plc_recorder', to=settings.AUTH_USER_MODEL)),
                ('timekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_plc_timekeeper', to=settings.AUTH_USER_MODEL)),
                ('actions', models.ManyToManyField(blank=True, related_name='plc_actions', to='mainapp.plcaction')),
                ('focus_topics', models.ManyToManyField(blank=True, related_name='plc_topics', to='mainapp.plctopic')),
            ],
        ),
    ]
