# Generated by Django 5.0.6 on 2024-11-21 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0082_alter_faq_type_plcaction_plctopic_plc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc',
            name='club',
        ),
        migrations.AddField(
            model_name='meeting',
            name='plc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc', to='mainapp.plc'),
        ),
        migrations.AlterField(
            model_name='plc',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc_facilitator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plc',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc_recorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plc',
            name='timekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_plc_timekeeper', to=settings.AUTH_USER_MODEL),
        ),
    ]
