# Generated by Django 5.0.6 on 2024-11-21 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0083_remove_plc_club_meeting_plc_alter_plc_facilitator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc',
            name='attending_Students',
        ),
        migrations.RemoveField(
            model_name='plc',
            name='confirmed_Students',
        ),
        migrations.AddField(
            model_name='plc',
            name='attended_Students',
            field=models.ManyToManyField(blank=True, related_name='plc_attended_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
