# Generated by Django 5.0.6 on 2024-11-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0084_remove_plc_attending_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plc',
            name='expiry',
        ),
    ]
