# Generated by Django 5.0.6 on 2024-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0086_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hos_approved',
            field=models.BooleanField(default=False),
        ),
    ]
